<?php

namespace App\Models\Product;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'Product';
    protected $primaryKey = 'Product_ID';
    public $timestamps = false;

    protected $fillable = [
        'Unit_Measurement_ID',
        'PrNumber',
        'PrActif',
        'PrSortKey1',
        'PrSortKey2',
        'PrProductGroupNumber',
        'PrDescription1',
        'PrDescription2',
        'PrDescription3',
        'PrComments',
        'PrShowComment',
        'PrPrintComInTrans',
        'PrProductBoAllowed',
        'PrBoAllowed',
        'PrStock',
        'PrMaxQty',
        'PrMinQty',
        'PrLibre1',
        'PrLibre2',
        'PrLibre3',
        'PrUser_ID',
        'PrPath',
        'Paper_ID',
        'Product_Cost',
        'Product_Paper_Width',
        'ProductCategorie_ID',
        'ProductType_ID',
        'PrRecCardPos',
        'Unit_Measurement_Factor',
        'Curency_ID',
        'Price_1',
        'Price_2',
        'Price_3',
        'Price_4',
        'Price_Suggest',
        'PrLibre4',
        'PrLibre5',
        'PrLibre6',
        'PrLibre7',
        'PrLibre8',
        'prTimeCreated',
        'prTimeModify',
        'prUserModify',
        'PrQtyMonthMax',
        'PrQtyMonthMin',
        'PrQuotation',
        'PrSubstitute',
        'Attachement',
        'UPCA',
        'Manufacturer_Name',
        'Manufacturer_Tel',
        'Random_Id',
        'is_Fast_mode',
        'Product_Lock',
        'Product_Lock_By',
        'Product_Lock_timestamp',
        'is_Price_Update_Cmd',
        'Unit_Measurement_ID_Cmd',
        'Unit_Measurement_ID_Price',
        'Unit_Measurement_ID_Ship',
        'Product_Comment_1',
        'Product_Comment_2',
        'Product_Date_1',
        'Product_Date_2',
        'Product_Date_3',
        'Product_Date_4',
        'Product_Has_Components',
        'Product_Numeric_1',
        'Product_Numeric_2',
        'Product_Numeric_3',
        'Product_Numeric_4',
        'Product_Text_1',
        'Product_Text_2',
        'Product_Text_3',
        'Product_Text_4',
        'M_Base',
        'Product_Standard_Size_ID',
        'Paper_Est_Code_GraphICC',
        'Attachement1',
        'Attachement2',
        'Attachement3',
        'Attachement4',
        'Core_Id',
        'Thickness',
        'PrUnitcode',
        'PrLongUnitCode',
        'PrLocation',
        'PrSequence',
        'PrUPC',
        'Product_Length',
        'Product_Price_CM2',
        'Is_Include_Production_Needs',
        'Is_Reprint_Est'
    ];
}
